services:
  backend:
    build: ./kiwi-social-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/kiwi_social_db
      - SPRING_DATASOURCE_USERNAME=daniel
      - SPRING_DATASOURCE_PASSWORD=daniel

    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: kiwi_social_db
      POSTGRES_USER: daniel
      POSTGRES_PASSWORD: daniel
    ports:
      - "5432:5432"
